=== TACC/agavepy/docs/_static/schema/JobRequest.json
{
  "$id": "http://agavepy.readthedocs.io/en/latest/JobRequest.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "appId": {
      "description": "The unique name of the application being run by this job. This must be a valid application that the calling user has permission to run.",
      "type": "string"
    },
    "archive": {
      "description": "Whether the output from this job should be archived. If true, all new files created by this application's execution will be archived to the archivePath in the user's default storage system.",
      "type": "boolean"
    },
    "archivePath": {
      "description": "The path of the archive folder for this job on the user's default storage sytem.",
      "type": "string"
    },
    "archiveSystem": {
      "description": "The unique id of the storage system on which this job's output will be staged.",
      "type": "string"
    },
    "batchQueue": {
      "description": "The queue to which this job should be submitted. This is optional and only applies when the execution system has a batch scheduler.",
      "type": "string"
    },
    "inputs": {
      "description": "The application specific input files needed for this job. These vary from application to application and should be entered as multiple individual parameters in the form. Inputs may be given as relative paths in the user's default storage system or as URI. If a URI is given, the data will be staged in by the IO service and made avaialble to the application at run time.",
      "type": "JobInputs"
    },
    "maxRunTime": {
      "description": "The requested compute time needed for this application to complete given in HH:mm:ss format.",
      "type": "string"
    },
    "memoryPerNode": {
      "description": "The requested memory for this application to run given in GB.",
      "type": "string"
    },
    "name": {
      "description": "The name of the job.",
      "type": "string"
    },
    "nodeCount": {
      "description": "The number of processors this application should utilize while running. If the application is not of executionType PARALLEL, this should be 1.",
      "type": "integer"
    },
    "notifications": {
      "description": "An array of notifications you wish to receive.",
      "type": "array"
    },
    "parameters": {
      "description": "The application specific parameters needed for this job. These vary from application to application and should be entered as multiple individual parameters in the form. The actual dataType will be determined by the application description.",
      "type": "JobParameters"
    },
    "processorsPerNode": {
      "description": "The number of processors this application should utilize while running. If the application is not of executionType PARALLEL, this should be 1.",
      "type": "integer"
    }
  },
  "required": [
    "inputs",
    "name",
    "parameters",
    "appId",
    "archive"
  ],
  "title": "AgavePy JobRequest schema",
  "type": "object"
}

=== TACC/agavepy/tests/data/integration/test-job.json
{
  "appId": "agavepy_sdk_wc-1.0.0",
  "archive": false,
  "archiveSystem": "test-storage-tacc-prod",
  "maxRunTime": "0:05:00",
  "inputs": {
    "input1": "agave://test-storage-tacc-prod/sd2etest/apps/agavepy_sdk_wc-1.0.0/example.txt"
  },
  "memoryPerNode": "1",
  "name": "agavepy_integration_test",
  "nodeCount": 1,
  "parameters": {},
  "processorsPerNode": 1
}
